use crate::bodies::*;
use crate::notes::*;
use crate::params::*;
use crate::schema::*;

pub(crate) static API_ENDPOINTS: &[ApiEndpoint] = &[
    ApiEndpoint {
        path: "/api/codex_apis",
        methods: GET_ONLY,
        description: "Return the public API catalog for this service.",
        operations: &[ApiOperation {
            method: "GET",
            description: "Return the machine-readable API catalog for external automation.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(CATALOG_RESPONSE_BODY),
            notes: CATALOG_NOTES,
            request_example: Some("/api/codex_apis"),
            response_example: Some(
                r#"{"format":"webclx_codex_api_catalog_v2","total":18,"endpoints":[{"path":"/api/entries","methods":["GET"],"description":"List files and directories under the current workspace path.","operations":[{"method":"GET","success_status":200}]}]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/entries",
        methods: GET_ONLY,
        description: "List files and directories under the current workspace path.",
        operations: &[ApiOperation {
            method: "GET",
            description: "List directory entries for a workspace-relative path.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: PATH_QUERY_OPTIONAL,
            request_body: None,
            response_body: Some(DIRECTORY_RESPONSE_BODY),
            notes: PATH_SCOPE_NOTES,
            request_example: Some("/api/entries?path=src"),
            response_example: Some(
                r#"{"path":"src","display_path":"/home/codes/webClx/src","parent_path":"","entries":[{"name":"main.rs","path":"src/main.rs","kind":"file","size":8192}]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/file",
        methods: GET_PUT,
        description: "Read or save a file by workspace-relative path.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "Read a UTF-8 text file.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: FILE_PATH_QUERY_REQUIRED,
                request_body: None,
                response_body: Some(FILE_RESPONSE_BODY),
                notes: FILE_READ_NOTES,
                request_example: Some("/api/file?path=src/main.rs"),
                response_example: Some(
                    r#"{"path":"src/main.rs","display_path":"/home/codes/webClx/src/main.rs","editable":true,"size":8192,"content":"fn main() {}\n","message":null}"#,
                ),
            },
            ApiOperation {
                method: "PUT",
                description: "Save a UTF-8 text file.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_FILE_REQUEST_BODY),
                response_body: Some(SAVE_FILE_RESPONSE_BODY),
                notes: FILE_SAVE_NOTES,
                request_example: Some(r#"{"path":"src/main.rs","content":"fn main() {}\n"}"#),
                response_example: Some(r#"{"ok":true,"saved_bytes":14}"#),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/file/rename",
        methods: POST_ONLY,
        description: "Rename a workspace file or directory.",
        operations: &[ApiOperation {
            method: "POST",
            description: "Rename an ordinary file or directory within its current parent directory.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(RENAME_PATH_REQUEST_BODY),
            response_body: Some(RENAME_PATH_RESPONSE_BODY),
            notes: FILE_RENAME_NOTES,
            request_example: Some(r#"{"path":"src/main.rs","name":"lib.rs"}"#),
            response_example: Some(
                r#"{"ok":true,"old_path":"src/main.rs","path":"src/lib.rs","display_path":"/home/codes/webClx/src/lib.rs","kind":"file"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/settings",
        methods: GET_PUT,
        description: "Read or update workspace settings.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "Return the current workspace settings.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(SETTINGS_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/settings"),
                response_example: Some(
                    r#"{"workspace_dir":"/home/codes","default_workspace_dir":"/home/codes","host_name":"openeuler","show_dot_entries":true,"show_all_workspace_sessions":true,"desktop_terminal_soft_keyboard_enabled":false,"terminal_soft_keyboard_scale":1.08,"favorite_paths":[],"workspace_history":[],"claude_model_options":[],"codex_config_key":"model","codex_config_value":"gpt-5.4","codex_secondary_config_key":"model_reasoning_effort","codex_secondary_config_value":"high","config_file":"/home/codes/webClx/webclx-settings.json"}"#,
                ),
            },
            ApiOperation {
                method: "PUT",
                description: "Partially update workspace settings.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_SETTINGS_REQUEST_BODY),
                response_body: Some(SAVE_SETTINGS_RESPONSE_BODY),
                notes: SETTINGS_SAVE_NOTES,
                request_example: Some(
                    r#"{"workspace_dir":"/home/codes/webClx","show_dot_entries":true,"show_all_workspace_sessions":true,"desktop_terminal_soft_keyboard_enabled":false,"terminal_soft_keyboard_scale":1.08,"workspace_history":[{"path":"/home/codes/webClx","last_opened_at":1712640000123}],"codex_config_key":"model","codex_config_value":"gpt-5.4","codex_secondary_config_key":"model_reasoning_effort","codex_secondary_config_value":"high"}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"workspace_dir":"/home/codes/webClx","show_dot_entries":true,"show_all_workspace_sessions":true,"desktop_terminal_soft_keyboard_enabled":false,"terminal_soft_keyboard_scale":1.08,"favorite_paths":[],"workspace_history":[{"path":"/home/codes/webClx","last_opened_at":1712640000123}],"claude_model_options":[],"codex_config_key":"model","codex_config_value":"gpt-5.4","codex_secondary_config_key":"model_reasoning_effort","codex_secondary_config_value":"high"}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/presets",
        methods: GET_POST,
        description: "List or create OpenAI-style auth presets.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "List saved login-style auth presets and current auth state.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(AUTH_PRESET_LIST_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/presets"),
                response_example: Some(
                    r#"{"auth_file":"/home/example/.codex/auth.json","config_file":"/home/example/.codex/config.toml","preset_file":"/home/codes/webClx/webclx-auth-presets.json","current_mode":"auth","current_auth":{"account_id":"acct_123456","short_id":"123456","email":"user@example.com","plan_type":"plus","last_refresh":"2026-04-09T00:00:00Z"},"current_api":null,"current_auth_error":null,"current_config_error":null,"presets":[]}"#,
                ),
            },
            ApiOperation {
                method: "POST",
                description: "Create a login-style auth preset.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_AUTH_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_AUTH_PRESET_RESPONSE_BODY),
                notes: SAVE_AUTH_NOTES,
                request_example: Some(
                    r#"{"name":"Main login","details":{"email":"user@example.com","plan_type":"plus"},"config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T00:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}}}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"auth-1712640000","name":"Main login","account_id":"acct_123456","last_refresh":"2026-04-09T00:00:00Z","saved_at":1712640000,"active":false,"details":{"email":"user@example.com","plan_type":"plus"},"config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T00:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}}}}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/api-presets",
        methods: GET_POST,
        description: "List or create generic API provider presets.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "List saved API-key presets and current API state.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(API_PRESET_LIST_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/api-presets"),
                response_example: Some(
                    r#"{"auth_file":"/home/example/.codex/auth.json","config_file":"/home/example/.codex/config.toml","preset_file":"/home/codes/webClx/webclx-api-presets.json","current_mode":"api","current_auth":null,"current_api":{"provider_id":"webclx_api","provider_name":"OpenAI","base_url":"https://api.openai.com/v1","wire_api":"responses","masked_api_key":"sk-...cret","preset_name":"OpenAI default","management_url":"https://platform.openai.com/api-keys"},"current_auth_error":null,"current_config_error":null,"presets":[]}"#,
                ),
            },
            ApiOperation {
                method: "POST",
                description: "Create an API-key preset.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_API_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_API_PRESET_RESPONSE_BODY),
                notes: SAVE_API_NOTES,
                request_example: Some(
                    r#"{"name":"OpenAI default","provider_name":"OpenAI","api_key":"sk-live-secret","base_url":"https://api.openai.com/v1","management_url":"https://platform.openai.com/api-keys","config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high"}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"api-1712640000","name":"OpenAI default","provider_name":"OpenAI","base_url":"https://api.openai.com/v1","management_url":"https://platform.openai.com/api-keys","config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","api_key":"sk-live-secret","masked_api_key":"sk-...cret","saved_at":1712640000,"active":false}}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/claude-presets",
        methods: GET_POST,
        description: "List or create Claude-compatible presets.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "List saved Claude presets and current Claude state.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(CLAUDE_PRESET_LIST_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/claude-presets"),
                response_example: Some(
                    r#"{"settings_file":"/home/example/.claude/settings.json","preset_file":"/home/codes/webClx/webclx-claude-presets.json","current_claude":{"provider_name":"Anthropic","base_url":"https://api.anthropic.com","management_url":"https://console.anthropic.com/settings/keys","default_haiku_model":"claude-3-5-haiku-latest","default_sonnet_model":"claude-sonnet-4-0","default_opus_model":"claude-opus-4-0","third_party_model":null,"masked_auth_token":"sk-ant-...cret","preset_name":"Anthropic default"},"current_settings_error":null,"presets":[]}"#,
                ),
            },
            ApiOperation {
                method: "POST",
                description: "Create a Claude preset.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_CLAUDE_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_CLAUDE_PRESET_RESPONSE_BODY),
                notes: SAVE_CLAUDE_NOTES,
                request_example: Some(
                    r#"{"name":"Anthropic default","provider_name":"Anthropic","auth_token":"sk-ant-secret","base_url":"https://api.anthropic.com","management_url":"https://console.anthropic.com/settings/keys","default_haiku_model":"claude-3-5-haiku-latest","default_sonnet_model":"claude-sonnet-4-0","default_opus_model":"claude-opus-4-0"}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"claude-1712640000","name":"Anthropic default","provider_name":"Anthropic","base_url":"https://api.anthropic.com","management_url":"https://console.anthropic.com/settings/keys","auth_token":"sk-ant-secret","masked_auth_token":"sk-ant-...cret","default_haiku_model":"claude-3-5-haiku-latest","default_sonnet_model":"claude-sonnet-4-0","default_opus_model":"claude-opus-4-0","third_party_model":null,"saved_at":1712640000,"active":false}}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/oauth/codex/start",
        methods: POST_ONLY,
        description: "Start the official Codex OAuth device-login flow.",
        operations: &[ApiOperation {
            method: "POST",
            description: "Request a Codex device user code, create a temporary polling session, and begin waiting for official-login completion.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(CODEX_OAUTH_SESSION_RESPONSE_BODY),
            notes: CODEX_OAUTH_NOTES,
            request_example: Some("/api/auth/oauth/codex/start"),
            response_example: Some(
                r#"{"ok":true,"session_id":"codex_xxx","status":"pending","verification_url":"https://auth.openai.com/codex/device","authorize_url":"https://auth.openai.com/codex/device?code=ABCD-EFGH","user_code":"ABCD-EFGH","poll_interval_seconds":5,"created_at":1712640000,"updated_at":1712640000,"expires_at":1712640900}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/oauth/codex/sessions/{session_id}",
        methods: GET_ONLY,
        description: "Poll the state of an official Codex OAuth device-login session.",
        operations: &[ApiOperation {
            method: "GET",
            description: "Return the latest device-login session state, including auth.json-compatible tokens after a successful official login.",
            success_status: 200,
            path_params: &[field(
                "session_id",
                "string",
                true,
                false,
                "Session id returned by the start API.",
                Some("codex_xxx"),
                EMPTY_TEXTS,
                EMPTY_FIELDS,
            )],
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(CODEX_OAUTH_SESSION_RESPONSE_BODY),
            notes: CODEX_OAUTH_NOTES,
            request_example: Some("/api/auth/oauth/codex/sessions/codex_xxx"),
            response_example: Some(
                r#"{"ok":true,"session_id":"codex_xxx","status":"completed","verification_url":"https://auth.openai.com/codex/device","authorize_url":"https://auth.openai.com/codex/device?code=ABCD-EFGH","user_code":"ABCD-EFGH","poll_interval_seconds":5,"created_at":1712640000,"updated_at":1712640025,"expires_at":1712640900,"auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-21T13:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}},"details":{"email":"user@example.com","plan_type":"PLUS","account_name":"Personal","login_method":"Google"},"suggested_name":"user@example.com · Personal"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/current",
        methods: PUT_ONLY,
        description: "Apply credentials from the current editor form.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Apply login-style auth data directly from the request body.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(APPLY_CURRENT_AUTH_REQUEST_BODY),
            response_body: Some(APPLY_CURRENT_AUTH_RESPONSE_BODY),
            notes: APPLY_CURRENT_AUTH_NOTES,
            request_example: Some(
                r#"{"auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T00:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}}}"#,
            ),
            response_example: Some(
                r#"{"ok":true,"auth_file":"/home/example/.codex/auth.json","config_file":"/home/example/.codex/config.toml","account_id":"acct_123456"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/presets/{preset_id}",
        methods: PUT_DELETE,
        description: "Update or delete a saved OpenAI-style auth preset.",
        operations: &[
            ApiOperation {
                method: "PUT",
                description: "Update an existing login-style auth preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_AUTH_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_AUTH_PRESET_RESPONSE_BODY),
                notes: SAVE_AUTH_NOTES,
                request_example: Some(
                    r#"PUT /api/auth/presets/auth-1712640000 {"name":"Main login","details":{"email":"user@example.com"},"config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T00:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}}}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"auth-1712640000","name":"Main login","account_id":"acct_123456","last_refresh":"2026-04-09T00:00:00Z","saved_at":1712640000,"active":false,"details":{"email":"user@example.com"},"config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T00:00:00Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_123456"}}}}"#,
                ),
            },
            ApiOperation {
                method: "DELETE",
                description: "Delete a login-style auth preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(DELETE_PRESET_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/presets/auth-1712640000"),
                response_example: Some(r#"{"ok":true,"deleted_id":"auth-1712640000"}"#),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/api-presets/{preset_id}",
        methods: PUT_DELETE,
        description: "Update or delete a saved generic API provider preset.",
        operations: &[
            ApiOperation {
                method: "PUT",
                description: "Update an existing API-key preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_API_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_API_PRESET_RESPONSE_BODY),
                notes: SAVE_API_NOTES,
                request_example: Some(
                    r#"PUT /api/auth/api-presets/api-1712640000 {"name":"OpenAI default","provider_name":"OpenAI","api_key":"sk-live-secret","base_url":"https://api.openai.com/v1","management_url":"https://platform.openai.com/api-keys","config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high"}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"api-1712640000","name":"OpenAI default","provider_name":"OpenAI","base_url":"https://api.openai.com/v1","management_url":"https://platform.openai.com/api-keys","config_key":"model","config_value":"glm-5.1","secondary_config_key":"model_reasoning_effort","secondary_config_value":"high","api_key":"sk-live-secret","masked_api_key":"sk-...cret","saved_at":1712640000,"active":false}}"#,
                ),
            },
            ApiOperation {
                method: "DELETE",
                description: "Delete an API-key preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(DELETE_PRESET_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/api-presets/api-1712640000"),
                response_example: Some(r#"{"ok":true,"deleted_id":"api-1712640000"}"#),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/claude-presets/{preset_id}",
        methods: PUT_DELETE,
        description: "Update or delete a saved Claude-compatible preset.",
        operations: &[
            ApiOperation {
                method: "PUT",
                description: "Update an existing Claude preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(SAVE_CLAUDE_PRESET_REQUEST_BODY),
                response_body: Some(SAVE_CLAUDE_PRESET_RESPONSE_BODY),
                notes: SAVE_CLAUDE_NOTES,
                request_example: Some(
                    r#"PUT /api/auth/claude-presets/claude-1712640000 {"name":"Anthropic default","provider_name":"Anthropic","auth_token":"sk-ant-secret","base_url":"https://api.anthropic.com","management_url":"https://console.anthropic.com/settings/keys","default_haiku_model":"claude-3-5-haiku-latest","default_sonnet_model":"claude-sonnet-4-0","default_opus_model":"claude-opus-4-0"}"#,
                ),
                response_example: Some(
                    r#"{"ok":true,"preset":{"id":"claude-1712640000","name":"Anthropic default","provider_name":"Anthropic","base_url":"https://api.anthropic.com","management_url":"https://console.anthropic.com/settings/keys","auth_token":"sk-ant-secret","masked_auth_token":"sk-ant-...cret","default_haiku_model":"claude-3-5-haiku-latest","default_sonnet_model":"claude-sonnet-4-0","default_opus_model":"claude-opus-4-0","third_party_model":null,"saved_at":1712640000,"active":false}}"#,
                ),
            },
            ApiOperation {
                method: "DELETE",
                description: "Delete a Claude preset.",
                success_status: 200,
                path_params: PRESET_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(DELETE_PRESET_RESPONSE_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/auth/claude-presets/claude-1712640000"),
                response_example: Some(r#"{"ok":true,"deleted_id":"claude-1712640000"}"#),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/auth/presets/{preset_id}/apply",
        methods: PUT_ONLY,
        description: "Apply a saved OpenAI-style auth preset.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Write a saved login-style auth preset into auth.json and sync config.toml.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(APPLY_AUTH_RESPONSE_BODY),
            notes: APPLY_PRESET_NOTES,
            request_example: Some("/api/auth/presets/auth-1712640000/apply"),
            response_example: Some(
                r#"{"ok":true,"preset_id":"auth-1712640000","name":"Main login","auth_file":"/home/example/.codex/auth.json","config_file":"/home/example/.codex/config.toml"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/presets/{preset_id}/refresh-quota",
        methods: PUT_ONLY,
        description: "Refresh Codex OAuth quota metadata for a saved auth preset.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Fetch latest usage windows from ChatGPT Codex and update the stored preset details.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(SAVE_AUTH_PRESET_RESPONSE_BODY),
            notes: &[
                "Requires a login-style auth preset with access_token and refresh_token.",
                "If the access token has expired, the server refreshes it first and persists the refreshed token bundle.",
                "If this preset is currently active, ~/.codex/auth.json is updated too.",
            ],
            request_example: Some("/api/auth/presets/auth-1712640000/refresh-quota"),
            response_example: Some(
                r#"{"ok":true,"preset":{"id":"auth-1712640000","name":"Main login","account_id":"acct_123456","last_refresh":"2026-04-09T12:34:56Z","saved_at":1712641200,"active":true,"details":{"email":"user@example.com","plan_type":"PLUS","hourly_percentage":36,"hourly_reset_time":1712643600,"weekly_percentage":75,"weekly_reset_time":1713248400},"auth":{"OPENAI_API_KEY":null,"last_refresh":"2026-04-09T12:34:56Z","tokens":{"access_token":"eyJ...","account_id":"acct_123456","id_token":"eyJ...","refresh_token":"rft_654321"}}}}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/presets/refresh-all-quotas",
        methods: PUT_ONLY,
        description: "Refresh Codex OAuth quota metadata for all saved auth presets.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Fetch latest usage windows from ChatGPT Codex for each saved auth preset and persist successful updates.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(REFRESH_ALL_AUTH_PRESETS_RESPONSE_BODY),
            notes: &[
                "Each preset uses the same refresh flow as the single-preset quota refresh API.",
                "Successful presets are persisted even if some other presets fail.",
                "If the currently active preset refreshes successfully, ~/.codex/auth.json is updated too.",
            ],
            request_example: Some("/api/auth/presets/refresh-all-quotas"),
            response_example: Some(
                r#"{"ok":true,"total":5,"success_count":4,"failure_count":1,"failures":[{"preset_id":"auth-1712640003","name":"备用账号","error":"刷新额度失败: HTTP 403"}]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/api-presets/{preset_id}/apply",
        methods: PUT_ONLY,
        description: "Apply a saved generic API provider preset.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Write a saved API-key preset into auth.json and config.toml, then read both files back and reject any mismatch.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(APPLY_API_RESPONSE_BODY),
            notes: APPLY_PRESET_NOTES,
            request_example: Some("/api/auth/api-presets/api-1712640000/apply"),
            response_example: Some(
                r#"{"ok":true,"preset_id":"api-1712640000","name":"OpenAI default","auth_file":"/home/example/.codex/auth.json","config_file":"/home/example/.codex/config.toml"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/agent/exec-with-preset",
        methods: POST_ONLY,
        description: "Run an isolated read-only Codex task with a saved API preset.",
        operations: &[ApiOperation {
            method: "POST",
            description: "Create a request-scoped Codex configuration, run ephemeral read-only codex exec in cwd, then delete the temporary configuration.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(EXEC_WITH_PRESET_REQUEST_BODY),
            response_body: Some(EXEC_WITH_PRESET_RESPONSE_BODY),
            notes: &[
                "This endpoint never applies the preset or modifies the terminal user's global auth.json/config.toml.",
                "The selected preset must not override isolation or credential environment variables.",
                "terminal_startup_script is rejected; only structured terminal_env is supported.",
                "A process or structured-output failure returns HTTP 200 with ok=false and error details; request validation returns HTTP 400.",
            ],
            request_example: Some(
                r#"{"preset":{"name":"DeepSeek Codex"},"cwd":"/home/codes/webClx","task":"Review the change without modifying files.","timeout_secs":600,"reasoning_effort":"high","output_schema":{"type":"object"}}"#,
            ),
            response_example: Some(
                r#"{"ok":true,"preset":{"id":"api-1712640000","name":"DeepSeek Codex","index":25,"model":"deepseek-v4-pro"},"cwd":"/home/codes/webClx","sandbox":"read-only","ephemeral":true,"elapsed_ms":1234,"exit_code":0,"output":"{\"status\":\"agree\"}","structured_output":{"status":"agree"}}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/api-presets/{preset_id}/verify",
        methods: GET_ONLY,
        description: "Verify a saved generic API provider preset against the current Codex files.",
        operations: &[ApiOperation {
            method: "GET",
            description: "Read auth.json and config.toml without modifying them, then compare the masked API state and model overrides with the saved preset.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(VERIFY_API_PRESET_RESPONSE_BODY),
            notes: &[
                "This endpoint is read-only and never applies the preset or changes active proxy state.",
                "API keys remain masked; mismatch messages identify fields but do not include secret or arbitrary config values.",
                "Errors are returned as plain-text bodies with HTTP 400, 404, or 500.",
            ],
            request_example: Some("/api/auth/api-presets/api-1712640000/verify"),
            response_example: Some(
                r#"{"ok":true,"preset_id":"api-1712640000","name":"OpenAI default","matches":true,"current_mode":"api","current_api":{"provider_id":"webclx_api","provider_name":"OpenAI","base_url":"https://api.openai.com/v1","wire_api":"responses","masked_api_key":"sk-...cret","preset_name":"OpenAI default","management_url":"https://platform.openai.com/api-keys"},"model":"glm-5.1","mismatches":[]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/claude-presets/{preset_id}/apply",
        methods: PUT_ONLY,
        description: "Apply a saved Claude-compatible preset to this app.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Write a saved Claude preset into ~/.claude/settings.json.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(APPLY_CLAUDE_RESPONSE_BODY),
            notes: APPLY_PRESET_NOTES,
            request_example: Some("/api/auth/claude-presets/claude-1712640000/apply"),
            response_example: Some(
                r#"{"ok":true,"preset_id":"claude-1712640000","name":"Anthropic default","settings_file":"/home/example/.claude/settings.json"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/auth/claude-presets/{preset_id}/apply-opencode",
        methods: PUT_ONLY,
        description: "Apply a saved Claude-compatible preset to OpenCode config.",
        operations: &[ApiOperation {
            method: "PUT",
            description: "Write a saved Claude preset into {workspace}/opencode.json.",
            success_status: 200,
            path_params: PRESET_ID_PATH_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: None,
            response_body: Some(APPLY_CLAUDE_RESPONSE_BODY),
            notes: APPLY_PRESET_NOTES,
            request_example: Some("/api/auth/claude-presets/claude-1712640000/apply-opencode"),
            response_example: Some(
                r#"{"ok":true,"preset_id":"claude-1712640000","name":"Anthropic default","settings_file":"/home/codes/webClx/opencode.json"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/build/compile",
        methods: POST_ONLY,
        description: "Queue a compile-only command without installing files or restarting services.",
        operations: &[ApiOperation {
            method: "POST",
            description: "Queue a pure compile request, run it from project_dir, and notify the source terminal when it finishes.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(COMPILE_REQUEST_BODY),
            response_body: Some(COMPILE_RESPONSE_BODY),
            notes: &[
                "Use this endpoint for compile or build checks that must not install files or restart a service.",
                "Compile logs are retained under the webClx-owned queue directory; the service does not create docs/logs or other log files in project_dir.",
                "Use /api/build/deploy when a successful compile must be followed by a project-owned install script.",
            ],
            request_example: Some(
                r#"{"source_terminal_name":"signIn_5","source_terminal_id":"s1547","source_tmux_session":"webclx_s1547","project_path":"signIn","project":"signIn","project_dir":"/home/codes/signIn","command":["cargo","build","--release"],"note":"Codex finished edits; please continue after compile","debounce_secs":0}"#,
            ),
            response_example: Some(
                r#"{"ok":true,"request_id":"1712640000000000000-1234","request_kind":"compile","project":"signIn","project_dir":"/home/codes/signIn","source_terminal_id":"s1547","source_terminal_name":"signIn_5","source_tmux_session":"webclx_s1547","queued":true,"debounce_secs":0,"command":["cargo","build","--release"],"install_command":[],"audit_paths":[],"queue_dir":"/home/codes/webClx/.webclx-compile-queue"}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/build/deploy",
        methods: POST_ONLY,
        description: "Queue a project compile followed by a script-backed install command and before/after file-update audit.",
        operations: &[ApiOperation {
            method: "POST",
            description: "Queue a deploy request. The worker snapshots candidate binaries and related files, runs the compile command, executes script-backed install_command after success, snapshots again, and notifies the requester terminal with a difference summary.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(DEPLOY_REQUEST_BODY),
            response_body: Some(COMPILE_RESPONSE_BODY),
            notes: &[
                "Use this endpoint for compile/deploy/update/restart work instead of running install scripts directly from Codex.",
                "install_command must explicitly invoke a deployment script. Compile-only callers should use /api/build/compile.",
                "Merged deploy completions are sent once per request using source_terminal_id, then source_tmux_session, then source_terminal_name.",
                "Add audit_paths when inferred Cargo binaries and command/script paths do not cover every file that should appear in the report.",
                "Build logs and install audit reports are retained under the webClx-owned queue directory, never under project_dir.",
            ],
            request_example: Some(
                r#"{"source_terminal_name":"signIn_5","source_terminal_id":"s1547","source_tmux_session":"webclx_s1547","project_path":"signIn","project":"signIn","project_dir":"/home/codes/signIn","command":["cargo","build","--release"],"install_command":["bash","scripts/install-service.sh"],"audit_paths":["/home/bin/signIn/signIn"],"note":"Codex finished edits; please deploy","debounce_secs":0}"#,
            ),
            response_example: Some(
                r#"{"ok":true,"request_id":"1712640000000000000-1234","request_kind":"deploy","project":"signIn","project_dir":"/home/codes/signIn","source_terminal_id":"s1547","source_terminal_name":"signIn_5","source_tmux_session":"webclx_s1547","queued":true,"debounce_secs":0,"command":["cargo","build","--release"],"install_command":["bash","scripts/install-service.sh"],"audit_paths":["/home/bin/signIn/signIn"]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/build/compile/status",
        methods: GET_ONLY,
        description: "Return current compile queue status.",
        operations: &[ApiOperation {
            method: "GET",
            description: "Inspect pending merged compile requests, active work, and optional run history.",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: COMPILE_STATUS_QUERY_FIELDS,
            request_body: None,
            response_body: Some(COMPILE_STATUS_RESPONSE_BODY),
            notes: &[
                "Omit include_history to preserve the full historical response.",
                "Use include_history=false for a small live-status response before loading history separately.",
            ],
            request_example: Some("/api/build/compile/status?include_history=false"),
            response_example: Some(
                r#"{"ok":true,"project":"webClx","queue_dir":"/home/bin/webclx/compile","pending_count":2,"run_count":1,"latest_log":"/home/bin/webclx/compile/runs/20260612T095400-1234/run.log","pending_requests":[],"runs":[{"run_id":"20260612T095400-1234","status":"success","request_count":2,"projects":["webClx"],"targets":["webClx_1"],"log_path":"/home/bin/webclx/compile/runs/20260612T095400-1234/run.log"}]}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/service/deploy",
        methods: POST_ONLY,
        description: "执行部署脚本替换二进制文件并重启指定的 systemd 服务。",
        operations: &[ApiOperation {
            method: "POST",
            description: "将提供的部署脚本写入临时文件并执行，成功后通过 systemd-run 重启指定服务。",
            success_status: 200,
            path_params: EMPTY_FIELDS,
            query_params: EMPTY_FIELDS,
            request_body: Some(SERVICE_DEPLOY_REQUEST_BODY),
            response_body: Some(SERVICE_DEPLOY_RESPONSE_BODY),
            notes: &[
                "此端点执行无编译步骤的纯二进制部署。",
                "script 字段接收完整的脚本内容（而非脚本路径），服务器负责写入临时文件、设置执行权限和清理。",
                "服务重启使用 systemd-run --on-active=1s 延迟调度，确保当前 HTTP 响应在重启前已返回。",
                "可选字段 source_terminal_name 和 source_terminal_id 用于向发起终端发送部署完成通知。",
            ],
            request_example: Some(
                r##"{"service_name":"webclx.service","script":"#!/bin/bash\ninstall -m 0755 /tmp/webclx /home/bin/webclx/webclx","binary_path":"/home/bin/webclx/webclx","source_terminal_name":"webClx_1","source_terminal_id":"s1547"}"##,
            ),
            response_example: Some(
                r#"{"ok":true,"service_name":"webclx.service","binary_path":"/home/bin/webclx/webclx","restarted":true}"#,
            ),
        }],
    },
    ApiEndpoint {
        path: "/api/terminal/sessions",
        methods: GET_POST,
        description: "List terminal sessions or create a new session.",
        operations: &[
            ApiOperation {
                method: "GET",
                description: "List terminal sessions for one directory or across all directories.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: LIST_SESSIONS_QUERY_FIELDS,
                request_body: None,
                response_body: Some(TERMINAL_SESSIONS_RESPONSE_BODY),
                notes: TERMINAL_LIST_NOTES,
                request_example: Some("/api/terminal/sessions?path=src"),
                response_example: Some(
                    r#"{"all":false,"path":"src","display_path":"/home/codes/webClx/src","sessions":[{"id":"1","name":"webClx-1","title":"cargo test","path":"src","display_path":"/home/codes/webClx/src","alive":true,"created_at":1712640000123,"last_opened_at":1712643600456}]}"#,
                ),
            },
            ApiOperation {
                method: "POST",
                description: "Create a terminal session in a directory.",
                success_status: 200,
                path_params: EMPTY_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(CREATE_SESSION_REQUEST_BODY),
                response_body: Some(TERMINAL_SESSION_INFO_BODY),
                notes: TERMINAL_CREATE_NOTES,
                request_example: Some(r#"{"path":"src"}"#),
                response_example: Some(
                    r#"{"id":"1","name":"webClx-1","title":null,"path":"src","display_path":"/home/codes/webClx/src","alive":true,"created_at":1712640000123,"last_opened_at":1712640000123}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/terminal/sessions/{session_id}",
        methods: PUT_DELETE,
        description: "Rename or delete a terminal session.",
        operations: &[
            ApiOperation {
                method: "PUT",
                description: "Rename a terminal session.",
                success_status: 200,
                path_params: SESSION_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: Some(RENAME_SESSION_REQUEST_BODY),
                response_body: Some(TERMINAL_SESSION_INFO_BODY),
                notes: TERMINAL_RENAME_NOTES,
                request_example: Some(r#"PUT /api/terminal/sessions/1 {"name":"backend-test"}"#),
                response_example: Some(
                    r#"{"id":"1","name":"backend-test","title":"cargo test","path":"src","display_path":"/home/codes/webClx/src","alive":true,"created_at":1712640000123,"last_opened_at":1712643600456}"#,
                ),
            },
            ApiOperation {
                method: "DELETE",
                description: "Terminate and remove a terminal session.",
                success_status: 200,
                path_params: SESSION_ID_PATH_FIELDS,
                query_params: EMPTY_FIELDS,
                request_body: None,
                response_body: Some(TERMINAL_SESSION_INFO_BODY),
                notes: APPLY_PRESET_NOTES,
                request_example: Some("/api/terminal/sessions/1"),
                response_example: Some(
                    r#"{"id":"1","name":"backend-test","title":"cargo test","path":"src","display_path":"/home/codes/webClx/src","alive":true,"created_at":1712640000123,"last_opened_at":1712643600456}"#,
                ),
            },
        ],
    },
    ApiEndpoint {
        path: "/api/terminal/ws",
        methods: WS_UPGRADE,
        description: "Upgrade to a WebSocket connection for a terminal session.",
        operations: &[ApiOperation {
            method: "GET",
            description: "Upgrade to websocket and stream terminal bytes.",
            success_status: 101,
            path_params: EMPTY_FIELDS,
            query_params: TERMINAL_WS_QUERY_FIELDS,
            request_body: None,
            response_body: Some(WS_UPGRADE_RESPONSE_BODY),
            notes: TERMINAL_WS_NOTES,
            request_example: Some("/api/terminal/ws?path=src&session_id=1"),
            response_example: Some(
                r#"client text frame: {"type":"input","data":"ls\n"}; client text frame: {"type":"resize","cols":120,"rows":32}; server binary frames: terminal output bytes"#,
            ),
        }],
    },
];
