import assert from "node:assert/strict";
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { workerTestEnvironment } from "./compile-worker-test-env.mjs";

const repoDir = resolve(new URL("..", import.meta.url).pathname);
const workerScript = join(
  repoDir,
  "docs/codex/skills/webclx-rebuild/scripts/compile-worker.sh",
);
const fixtureRoot = mkdtempSync(join(tmpdir(), "webclx-required-artifacts-"));
const projectDir = join(fixtureRoot, "project");
const queueDir = join(fixtureRoot, "queue");
const installsLog = join(fixtureRoot, "installs.log");

mkdirSync(projectDir, { recursive: true });
mkdirSync(join(queueDir, "requests"), { recursive: true });
writeFileSync(join(projectDir, "existing.bin"), "ready\n");

const sharedInstall = [
  "bash",
  "-c",
  `printf 'installed\\n' >> ${JSON.stringify(installsLog)}`,
];
const requests = [
  {
    request_id: "generated-artifact",
    command: ["bash", "-c", "touch generated.bin"],
    install_command: ["bash", "-c", "touch generated-installed"],
    required_artifacts: ["generated.bin"],
  },
  {
    request_id: "existing-artifact",
    command: ["true"],
    install_command: sharedInstall,
    required_artifacts: ["existing.bin"],
  },
  {
    request_id: "failed-install",
    command: ["true"],
    install_command: ["false"],
    required_artifacts: ["existing.bin"],
  },
  {
    request_id: "missing-artifact",
    command: ["true"],
    install_command: sharedInstall,
    required_artifacts: ["missing.bin"],
  },
];

for (const request of requests) {
  writeFileSync(
    join(queueDir, `requests/${request.request_id}.json`),
    JSON.stringify({
      ...request,
      request_kind: "deploy",
      project: "artifact-fixture",
      project_dir: projectDir,
      project_path: "artifact-fixture",
    }),
  );
}

const result = spawnSync(
  "bash",
  [
    workerScript,
    "--queue-dir",
    queueDir,
    "--repo-dir",
    repoDir,
    "--work-dir",
    join(fixtureRoot, "worker-cache"),
    "--command-timeout",
    "10",
  ],
  { encoding: "utf8", env: workerTestEnvironment() },
);

try {
  assert.equal(result.status, 0, result.stderr);
  assert.equal(
    readFileSync(installsLog, "utf8"),
    "installed\n",
    "the missing-artifact spec must not execute its install command",
  );
  assert.equal(
    readFileSync(join(projectDir, "generated-installed"), "utf8"),
    "",
    "an artifact generated by the compile command must permit install",
  );

  const runDirs = readdirSync(join(queueDir, "runs")).map((runName) =>
    join(queueDir, "runs", runName),
  );
  const specs = runDirs.flatMap((runDir) =>
    readFileSync(join(runDir, "specs.jsonl"), "utf8")
      .trim()
      .split("\n")
      .filter(Boolean)
      .map((line) => JSON.parse(line)),
  );
  assert.equal(specs.length, 4, "required artifacts and install commands must participate in spec identity");
  assert.deepEqual(
    specs.map((spec) => spec.required_artifacts).sort(),
    [["existing.bin"], ["existing.bin"], ["generated.bin"], ["missing.bin"]],
  );
  const statuses = runDirs
    .flatMap((runDir) => readdirSync(runDir).map((name) => [runDir, name]))
    .filter(([, name]) => name.startsWith("status-"))
    .map(([runDir, name]) => Number(readFileSync(join(runDir, name), "utf8").trim()))
    .sort();
  assert.deepEqual(statuses, [0, 0, 1, 1]);
  const failedInstallRun = runDirs.find((runDir) =>
    readdirSync(runDir).some((name) =>
      name === "failed-install.json",
    ),
  );
  assert.ok(failedInstallRun, "the failed install run should be retained");
  assert.equal(
    readdirSync(failedInstallRun).some((name) => name.startsWith("deploy-succeeded-")),
    false,
    "a failed install must not create a successful deployment marker",
  );

  const logs = runDirs
    .flatMap((runDir) =>
      readdirSync(runDir)
        .filter((name) => name.startsWith("build-"))
        .map((name) => readFileSync(join(runDir, name), "utf8")),
    )
    .join("\n");
  assert.match(logs, /required artifact present: .*generated\.bin/);
  assert.match(logs, /required artifact missing: .*missing\.bin/);
  assert.equal(
    existsSync(join(projectDir, "docs/logs")),
    false,
    "the compile API must not create a log directory in the client source tree",
  );
  assert.ok(
    runDirs.some((runDir) =>
      readdirSync(runDir).some((name) =>
        name.startsWith("install-report-"),
      ),
    ),
    "deploy audit reports should be retained with the webClx-owned run",
  );
} finally {
  rmSync(fixtureRoot, { recursive: true, force: true });
}

console.log("compile worker required artifact tests passed");
