use crate::schema::*;

pub(crate) const AUTH_PRESET_DETAILS_FIELDS: &[ApiField] = &[
    field(
        "email",
        "string",
        false,
        true,
        "Account email if known.",
        Some("user@example.com"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "plan_type",
        "string",
        false,
        true,
        "Account plan label if known.",
        Some("plus"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "account_name",
        "string",
        false,
        true,
        "Friendly account name if known.",
        Some("Personal"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "login_method",
        "string",
        false,
        true,
        "Login provider label if known.",
        Some("password"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "hourly_percentage",
        "integer",
        false,
        true,
        "Hourly quota usage percentage.",
        Some("15"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "hourly_reset_time",
        "integer",
        false,
        true,
        "Unix timestamp for the hourly reset.",
        Some("1712643600"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "weekly_percentage",
        "integer",
        false,
        true,
        "Weekly quota usage percentage.",
        Some("60"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "weekly_reset_time",
        "integer",
        false,
        true,
        "Unix timestamp for the weekly reset.",
        Some("1713248400"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const AUTH_TOKEN_FIELDS: &[ApiField] = &[
    field(
        "access_token",
        "string",
        true,
        false,
        "Bearer access token.",
        Some("eyJhbGciOi..."),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "account_id",
        "string",
        true,
        false,
        "OpenAI account identifier.",
        Some("acct_123456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "id_token",
        "string",
        false,
        true,
        "Optional identity token.",
        Some("eyJhbGciOi..."),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "refresh_token",
        "string",
        false,
        true,
        "Optional refresh token used for re-authentication.",
        Some("rft_123456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const AUTH_FILE_FIELDS: &[ApiField] = &[
    field(
        "OPENAI_API_KEY",
        "string",
        false,
        true,
        "Optional API key retained inside login-format auth.json.",
        Some("sk-optional"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "last_refresh",
        "string",
        true,
        false,
        "Refresh timestamp string stored in auth.json.",
        Some("2026-04-09T00:00:00Z"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "tokens",
        "object",
        true,
        false,
        "Login token bundle.",
        None,
        EMPTY_TEXTS,
        AUTH_TOKEN_FIELDS,
    ),
];

pub(crate) const CURRENT_AUTH_FIELDS: &[ApiField] = &[
    field(
        "account_id",
        "string",
        true,
        false,
        "Current logged-in account id.",
        Some("acct_123456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "short_id",
        "string",
        true,
        false,
        "Short suffix of the account id.",
        Some("123456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "email",
        "string",
        true,
        true,
        "Resolved account email if available.",
        Some("user@example.com"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "plan_type",
        "string",
        true,
        true,
        "Resolved plan label if available.",
        Some("plus"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "last_refresh",
        "string",
        true,
        false,
        "Refresh timestamp string from auth.json.",
        Some("2026-04-09T00:00:00Z"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const CURRENT_API_FIELDS: &[ApiField] = &[
    field(
        "provider_id",
        "string",
        true,
        true,
        "Provider identifier from config.toml.",
        Some("webclx_api"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "provider_name",
        "string",
        true,
        true,
        "Provider display name.",
        Some("OpenAI"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "base_url",
        "string",
        true,
        true,
        "Provider base URL.",
        Some("https://api.openai.com/v1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "wire_api",
        "string",
        true,
        true,
        "Configured wire API mode.",
        Some("responses"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "masked_api_key",
        "string",
        true,
        true,
        "Masked API key for display only.",
        Some("sk-...abcd"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "preset_name",
        "string",
        true,
        true,
        "Matched preset name if one is active.",
        Some("OpenAI default"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "management_url",
        "string",
        true,
        true,
        "Management page URL if available.",
        Some("https://platform.openai.com/api-keys"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const CURRENT_CLAUDE_FIELDS: &[ApiField] = &[
    field(
        "provider_name",
        "string",
        true,
        true,
        "Claude provider name.",
        Some("Anthropic"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "base_url",
        "string",
        true,
        true,
        "Claude-compatible base URL.",
        Some("https://api.anthropic.com"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "management_url",
        "string",
        true,
        true,
        "Management page URL if available.",
        Some("https://console.anthropic.com/settings/keys"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_haiku_model",
        "string",
        true,
        true,
        "Default Haiku model override.",
        Some("claude-3-5-haiku-latest"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_sonnet_model",
        "string",
        true,
        true,
        "Default Sonnet model override.",
        Some("claude-sonnet-4-0"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_opus_model",
        "string",
        true,
        true,
        "Default Opus model override.",
        Some("claude-opus-4-0"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "third_party_model",
        "string",
        true,
        true,
        "Single custom model used instead of official trio fields.",
        Some("claude-3-7-sonnet"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "masked_auth_token",
        "string",
        true,
        true,
        "Masked Claude auth token.",
        Some("sk-ant-...abcd"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "preset_name",
        "string",
        true,
        true,
        "Matched preset name if one is active.",
        Some("Anthropic default"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const AUTH_PRESET_SUMMARY_FIELDS: &[ApiField] = &[
    field(
        "id",
        "string",
        true,
        false,
        "Preset id used in update/apply/delete routes.",
        Some("auth-1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "name",
        "string",
        true,
        false,
        "Preset display name.",
        Some("Main login"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "account_id",
        "string",
        true,
        false,
        "Account id extracted from the preset.",
        Some("acct_123456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "last_refresh",
        "string",
        true,
        false,
        "Refresh timestamp string.",
        Some("2026-04-09T00:00:00Z"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "saved_at",
        "integer",
        true,
        false,
        "Unix timestamp in seconds when the preset was stored.",
        Some("1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "active",
        "boolean",
        true,
        false,
        "Whether the preset currently matches active auth.json.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "details",
        "object",
        true,
        false,
        "Derived preset metadata.",
        None,
        EMPTY_TEXTS,
        AUTH_PRESET_DETAILS_FIELDS,
    ),
    field(
        "config_key",
        "string",
        true,
        true,
        "Optional top-level config.toml key override applied when switching this preset. Empty means use the settings default key.",
        Some("model"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "config_value",
        "string",
        true,
        true,
        "Optional value override written to the selected config.toml key when switching this preset. Empty means use the settings default value.",
        Some("glm-5.1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "secondary_config_key",
        "string",
        true,
        true,
        "Optional second top-level config.toml key override applied when switching this preset. Empty means use the settings default second key.",
        Some("model_reasoning_effort"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "secondary_config_value",
        "string",
        true,
        true,
        "Optional second value override written to the selected config.toml key when switching this preset. Empty means use the settings default second value.",
        Some("high"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "auth",
        "object",
        true,
        false,
        "Raw auth.json-compatible payload.",
        None,
        EMPTY_TEXTS,
        AUTH_FILE_FIELDS,
    ),
];

pub(crate) const API_PRESET_SUMMARY_FIELDS: &[ApiField] = &[
    field(
        "id",
        "string",
        true,
        false,
        "Preset id used in update/apply/delete routes.",
        Some("api-1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "name",
        "string",
        true,
        false,
        "Preset display name.",
        Some("OpenAI default"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "provider_name",
        "string",
        true,
        false,
        "Provider display name.",
        Some("OpenAI"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "base_url",
        "string",
        true,
        false,
        "Provider base URL without trailing slash.",
        Some("https://api.openai.com/v1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "management_url",
        "string",
        true,
        true,
        "Management page URL if available.",
        Some("https://platform.openai.com/api-keys"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "config_key",
        "string",
        true,
        true,
        "Optional top-level config.toml key override applied when switching this preset. Empty means use the settings default key.",
        Some("model"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "config_value",
        "string",
        true,
        true,
        "Optional value override written to the selected config.toml key when switching this preset. Empty means use the settings default value.",
        Some("glm-5.1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "secondary_config_key",
        "string",
        true,
        true,
        "Optional second top-level config.toml key override applied when switching this preset. Empty means use the settings default second key.",
        Some("model_reasoning_effort"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "secondary_config_value",
        "string",
        true,
        true,
        "Optional second value override written to the selected config.toml key when switching this preset. Empty means use the settings default second value.",
        Some("high"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "api_key",
        "string",
        true,
        false,
        "Stored API key.",
        Some("sk-live-secret"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "masked_api_key",
        "string",
        true,
        false,
        "Masked API key for display.",
        Some("sk-...cret"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "saved_at",
        "integer",
        true,
        false,
        "Unix timestamp in seconds when the preset was stored.",
        Some("1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "active",
        "boolean",
        true,
        false,
        "Whether the preset currently matches active API mode.",
        Some("false"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
];

pub(crate) const CLAUDE_PRESET_SUMMARY_FIELDS: &[ApiField] = &[
    field(
        "id",
        "string",
        true,
        false,
        "Preset id used in update/apply/delete routes.",
        Some("claude-1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "name",
        "string",
        true,
        false,
        "Preset display name.",
        Some("Anthropic default"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "provider_name",
        "string",
        true,
        false,
        "Provider display name.",
        Some("Anthropic"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "base_url",
        "string",
        true,
        false,
        "Claude-compatible base URL.",
        Some("https://api.anthropic.com"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "management_url",
        "string",
        true,
        true,
        "Management page URL if available.",
        Some("https://console.anthropic.com/settings/keys"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "auth_token",
        "string",
        true,
        false,
        "Stored Claude auth token.",
        Some("sk-ant-secret"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "masked_auth_token",
        "string",
        true,
        false,
        "Masked Claude auth token for display.",
        Some("sk-ant-...cret"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_haiku_model",
        "string",
        true,
        true,
        "Default Haiku model override.",
        Some("claude-3-5-haiku-latest"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_sonnet_model",
        "string",
        true,
        true,
        "Default Sonnet model override.",
        Some("claude-sonnet-4-0"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "default_opus_model",
        "string",
        true,
        true,
        "Default Opus model override.",
        Some("claude-opus-4-0"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "third_party_model",
        "string",
        true,
        true,
        "Single custom model override.",
        Some("claude-3-7-sonnet"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "saved_at",
        "integer",
        true,
        false,
        "Unix timestamp in seconds when the preset was stored.",
        Some("1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "active",
        "boolean",
        true,
        false,
        "Whether the preset currently matches settings.json.",
        Some("false"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
];
