use crate::schema::*;

pub(crate) const PARAM_SCHEMA_META_FIELDS: &[ApiField] = &[
    field(
        "name",
        "string",
        true,
        false,
        "Parameter or field name.",
        Some("path"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "type",
        "string",
        true,
        false,
        "Scalar or structured type name.",
        Some("string"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "required",
        "boolean",
        true,
        false,
        "Whether callers must send the field.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "nullable",
        "boolean",
        true,
        false,
        "Whether null is allowed when the field is present.",
        Some("false"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "description",
        "string",
        true,
        false,
        "Human-readable behavior note.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "example",
        "string",
        true,
        true,
        "Example value as a string.",
        Some("src/main.rs"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "enum_values",
        "array<string>",
        true,
        false,
        "Allowed enum values when the field is enumerated.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "fields",
        "array<object>",
        true,
        false,
        "Nested object or array item fields.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const BODY_SCHEMA_META_FIELDS: &[ApiField] = &[
    field(
        "content_type",
        "string",
        true,
        false,
        "Expected content type.",
        Some("application/json"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "type",
        "string",
        true,
        false,
        "Top-level body type.",
        Some("object"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "description",
        "string",
        true,
        false,
        "Body summary.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "fields",
        "array<object>",
        true,
        false,
        "Top-level object fields or array item fields.",
        None,
        EMPTY_TEXTS,
        PARAM_SCHEMA_META_FIELDS,
    ),
];

pub(crate) const OPERATION_META_FIELDS: &[ApiField] = &[
    field(
        "method",
        "string",
        true,
        false,
        "HTTP method.",
        Some("GET"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "description",
        "string",
        true,
        false,
        "Operation summary.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "success_status",
        "integer",
        true,
        false,
        "Successful status code.",
        Some("200"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "path_params",
        "array<object>",
        true,
        false,
        "Path parameter schema list.",
        None,
        EMPTY_TEXTS,
        PARAM_SCHEMA_META_FIELDS,
    ),
    field(
        "query_params",
        "array<object>",
        true,
        false,
        "Query parameter schema list.",
        None,
        EMPTY_TEXTS,
        PARAM_SCHEMA_META_FIELDS,
    ),
    field(
        "request_body",
        "object",
        true,
        true,
        "Request body schema when the operation consumes a body.",
        None,
        EMPTY_TEXTS,
        BODY_SCHEMA_META_FIELDS,
    ),
    field(
        "response_body",
        "object",
        true,
        true,
        "Success response body schema.",
        None,
        EMPTY_TEXTS,
        BODY_SCHEMA_META_FIELDS,
    ),
    field(
        "notes",
        "array<string>",
        true,
        false,
        "Operational notes and constraints.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "request_example",
        "string",
        true,
        true,
        "Example request URL or JSON payload.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "response_example",
        "string",
        true,
        true,
        "Example success response.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];

pub(crate) const ENDPOINT_META_FIELDS: &[ApiField] = &[
    field(
        "path",
        "string",
        true,
        false,
        "Route path.",
        Some("/api/file"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "methods",
        "array<string>",
        true,
        false,
        "Supported methods for the route.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "description",
        "string",
        true,
        false,
        "Route summary.",
        None,
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "operations",
        "array<object>",
        true,
        false,
        "Per-method request and response schema entries.",
        None,
        EMPTY_TEXTS,
        OPERATION_META_FIELDS,
    ),
];
