use crate::schema::*;

pub(crate) const TERMINAL_SESSION_INFO_FIELDS: &[ApiField] = &[
    field(
        "id",
        "string",
        true,
        false,
        "Session id used by rename/delete/ws routes.",
        Some("1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "name",
        "string",
        true,
        false,
        "Display name shown in the UI.",
        Some("webClx-1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "title",
        "string",
        true,
        true,
        "Current terminal title if one was captured.",
        Some("cargo test"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "codex_api_preset_name",
        "string",
        true,
        false,
        "Launch-time Codex_API preset display name captured for the terminal session.",
        Some("OpenAI default"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "codex_api_base_url",
        "string",
        true,
        false,
        "Launch-time Codex_API base URL kept for compatibility with older session details.",
        Some("https://api.openai.com/v1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "path",
        "string",
        true,
        false,
        "Workspace-relative session directory.",
        Some("src"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "display_path",
        "string",
        true,
        false,
        "Human-readable absolute path.",
        Some("/home/codes/webClx/src"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "alive",
        "boolean",
        true,
        false,
        "Whether the session is alive when listed.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "connected",
        "boolean",
        true,
        false,
        "Whether a browser/web terminal is currently attached, enabling raw PTY input.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "busy",
        "boolean",
        true,
        false,
        "Whether the session appears active from agent-process or recent-output signals.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "activity_state",
        "string",
        true,
        false,
        "Activity signal category: working, error, retrying, ready, agent, recent_output, or idle.",
        Some("ready"),
        &[
            "working",
            "error",
            "retrying",
            "ready",
            "agent",
            "recent_output",
            "idle",
        ],
        EMPTY_FIELDS,
    ),
    field(
        "activity_label",
        "string",
        true,
        false,
        "Short UI label for terminal activity; agent state carries Codex/Claude labels.",
        Some("Codex"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "activity_agent",
        "string",
        true,
        true,
        "Detected terminal agent name when Codex or Claude is running.",
        Some("Codex"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "last_output_at",
        "integer",
        true,
        false,
        "Unix timestamp in milliseconds for the last observed live output chunk.",
        Some("1712643600456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "idle",
        "boolean",
        true,
        false,
        "Whether the session is in the idle dropdown.",
        Some("false"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
    field(
        "created_at",
        "integer",
        true,
        false,
        "Unix timestamp in milliseconds when the session was created.",
        Some("1712640000123"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "last_opened_at",
        "integer",
        true,
        false,
        "Unix timestamp in milliseconds for last open time.",
        Some("1712643600456"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
];
