use crate::schema::*;

const PRESET_SELECTOR_FIELDS: &[ApiField] = &[
    field(
        "id",
        "string",
        false,
        false,
        "Exact saved API preset id. Mutually exclusive with name, model, index, and current.",
        Some("api-1712640000"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "model",
        "string",
        false,
        false,
        "Exact case-insensitive model from config_overrides; selects the first match in saved order.",
        Some("gpt-5.6-sol"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "name",
        "string",
        false,
        false,
        "Exact case-insensitive saved API preset name. Duplicate names are rejected.",
        Some("DeepSeek Codex"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "index",
        "integer",
        false,
        false,
        "Zero-based saved-order index; negative values count from the end.",
        Some("-1"),
        EMPTY_TEXTS,
        EMPTY_FIELDS,
    ),
    field(
        "current",
        "boolean",
        false,
        false,
        "Resolve the currently applied saved API preset.",
        Some("true"),
        BOOL_VALUES,
        EMPTY_FIELDS,
    ),
];

pub(crate) const EXEC_WITH_PRESET_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Run one isolated read-only Codex task with a saved API preset.",
    &[
        field(
            "preset",
            "object",
            true,
            false,
            "Exactly one saved API preset selector.",
            None,
            EMPTY_TEXTS,
            PRESET_SELECTOR_FIELDS,
        ),
        field(
            "cwd",
            "string",
            true,
            false,
            "Existing absolute working directory for codex exec.",
            Some("/home/codes/webClx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "task",
            "string",
            true,
            false,
            "Natural-language read-only task.",
            Some("Review the proposed change without modifying files."),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "timeout_secs",
            "integer",
            false,
            false,
            "Per-call timeout from 1 through 1800 seconds.",
            Some("600"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "reasoning_effort",
            "string",
            false,
            false,
            "Optional Codex reasoning effort override.",
            Some("high"),
            &["none", "minimal", "low", "medium", "high", "xhigh"],
            EMPTY_FIELDS,
        ),
        field(
            "output_schema",
            "object",
            false,
            false,
            "Optional JSON Schema for the final response.",
            Some(r#"{"type":"object"}"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const EXEC_WITH_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Result of an isolated read-only Codex execution.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether execution and output parsing succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset",
            "object",
            true,
            false,
            "Resolved saved preset identity and model.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "cwd",
            "string",
            true,
            false,
            "Canonical working directory.",
            Some("/home/codes/webClx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "sandbox",
            "string",
            true,
            false,
            "Enforced Codex sandbox mode.",
            Some("read-only"),
            &["read-only"],
            EMPTY_FIELDS,
        ),
        field(
            "ephemeral",
            "boolean",
            true,
            false,
            "Whether Codex session persistence is disabled.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "elapsed_ms",
            "integer",
            true,
            false,
            "Execution duration in milliseconds.",
            Some("1234"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "exit_code",
            "integer",
            true,
            false,
            "Codex process exit code; -1 for timeout.",
            Some("0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "output",
            "string",
            true,
            false,
            "Final Codex message.",
            Some("{\"status\":\"agree\"}"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "structured_output",
            "object",
            false,
            true,
            "Parsed JSON final message when output_schema was requested.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "error",
            "string",
            false,
            true,
            "Execution or output parsing error.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);
