use crate::schema::*;

pub(crate) const COMPILE_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Queue a debounced single-flight project compile request.",
    &[
        field(
            "source_terminal_name",
            "string",
            true,
            false,
            "webClx terminal name submitted by the caller; the server resolves and stores the stable session id for completion notification when possible.",
            Some("webClx#2"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_id",
            "string",
            false,
            false,
            "Optional stable webClx terminal session id. When present and valid, completion notification uses this before the terminal name.",
            Some("s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_tmux_session",
            "string",
            false,
            false,
            "Optional tmux session name for diagnostics and notification fallback, typically derived from source_terminal_id.",
            Some("webclx_s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project_path",
            "string",
            false,
            false,
            "Project/workspace label shown in completion callbacks.",
            Some("signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project",
            "string",
            false,
            false,
            "Project name shown in responses and completion callbacks.",
            Some("signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project_dir",
            "string",
            false,
            false,
            "Absolute working directory where the compile command should run.",
            Some("/home/codes/signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "command",
            "array",
            false,
            false,
            "Command argv array to execute in project_dir. If omitted, the service infers a project command.",
            Some(r#"["cargo","build","--release"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "note",
            "string",
            false,
            false,
            "Optional note echoed back in the completion message.",
            Some("Codex finished edits and requested rebuild"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "debounce_secs",
            "integer",
            false,
            false,
            "Optional quiet window before compiling so nearby requests for the same project are merged.",
            Some("0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "skip_sync",
            "boolean",
            false,
            false,
            "Skip static file sync only when the request explicitly allows it.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "skip_restart",
            "boolean",
            false,
            false,
            "Skip systemd restart only when the request explicitly allows it.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const DEPLOY_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Queue a compile request followed by an install command and file-update audit.",
    &[
        field(
            "source_terminal_name",
            "string",
            true,
            false,
            "webClx terminal name submitted by the caller; the server resolves and stores the stable session id for completion notification when possible.",
            Some("webClx#2"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_id",
            "string",
            false,
            false,
            "Optional stable webClx terminal session id. When present and valid, completion notification uses this before the terminal name.",
            Some("s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_tmux_session",
            "string",
            false,
            false,
            "Optional tmux session name for diagnostics and notification fallback, typically derived from source_terminal_id.",
            Some("webclx_s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project_path",
            "string",
            false,
            false,
            "Project/workspace label shown in completion callbacks.",
            Some("signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project",
            "string",
            false,
            false,
            "Project name shown in responses and completion callbacks.",
            Some("signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project_dir",
            "string",
            false,
            false,
            "Absolute working directory where compile and install commands should run.",
            Some("/home/codes/signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "command",
            "array",
            false,
            false,
            "Compile command argv array to execute first. If omitted, the service infers a project build command.",
            Some(r#"["cargo","build","--release"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "install_command",
            "array",
            true,
            false,
            "Install/deploy command argv array to execute after compile succeeds. It must explicitly invoke a deployment script; compile-only callers should use /api/build/compile.",
            Some(r#"["bash","scripts/install-service.sh"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "audit_paths",
            "array",
            false,
            false,
            "Additional files or directories to snapshot before compile and after install. Cargo binaries and visible command/script paths are inferred automatically when possible.",
            Some(r#"["/home/bin/signIn/signIn"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "note",
            "string",
            false,
            false,
            "Optional note echoed back in the completion message.",
            Some("Codex finished edits and requested deploy"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "debounce_secs",
            "integer",
            false,
            false,
            "Optional quiet window before compiling so nearby requests for the same project are merged.",
            Some("0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SERVICE_DEPLOY_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "执行部署脚本替换二进制文件并重启 systemd 服务。",
    &[
        field(
            "service_name",
            "string",
            true,
            false,
            "systemd 服务名称，例如 webclx.service 或 my-app.service",
            Some("webclx.service"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "script",
            "string",
            true,
            false,
            "部署脚本完整内容（非脚本路径），由服务器写入临时文件后执行",
            Some("#!/bin/bash\ninstall -m 0755 /tmp/my-binary /home/bin/my-app/my-app"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "binary_path",
            "string",
            true,
            false,
            "要替换的目标二进制文件的绝对路径",
            Some("/home/bin/my-app/my-app"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_name",
            "string",
            false,
            false,
            "可选：接收部署完成通知的 webClx 终端名称",
            Some("webClx#2"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_id",
            "string",
            false,
            false,
            "可选：接收部署完成通知的稳定终端会话 ID",
            Some("s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SERVICE_DEPLOY_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "部署请求执行结果。",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "部署请求是否成功执行",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "service_name",
            "string",
            true,
            false,
            "已重启的系统服务名称",
            Some("webclx.service"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "binary_path",
            "string",
            true,
            false,
            "替换的目标二进制文件路径",
            Some("/home/bin/webclx/webclx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "restarted",
            "boolean",
            true,
            false,
            "服务是否已成功提交重启",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const COMPILE_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Compile queue acknowledgement.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "True when the request was queued.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "request_id",
            "string",
            true,
            false,
            "Unique queued request id.",
            Some("1712640000000000000-1234"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "request_kind",
            "string",
            true,
            false,
            "Queued request type: compile or deploy.",
            Some("deploy"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project",
            "string",
            true,
            false,
            "Compiled project name.",
            Some("signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "project_dir",
            "string",
            true,
            false,
            "Working directory used for the compile command.",
            Some("/home/codes/signIn"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_name",
            "string",
            true,
            false,
            "Terminal name resolved when the request was accepted.",
            Some("webClx#2"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_terminal_id",
            "string",
            false,
            false,
            "Stable terminal session id used for completion notification when the request target can be resolved.",
            Some("s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "source_tmux_session",
            "string",
            false,
            false,
            "tmux session name captured for diagnostics and notification fallback.",
            Some("webclx_s1547"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "queued",
            "boolean",
            true,
            false,
            "Whether the request is queued for a merged compile run.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "debounce_secs",
            "integer",
            true,
            false,
            "Quiet window used by the queue when explicitly requested.",
            Some("0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "command",
            "array",
            true,
            false,
            "Command argv array queued for the project.",
            Some(r#"["cargo","build","--release"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "install_command",
            "array",
            false,
            false,
            "Install command argv array for deploy requests.",
            Some(r#"["bash","scripts/install-service.sh"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "audit_paths",
            "array",
            false,
            false,
            "Additional audit paths for deploy requests.",
            Some(r#"["/home/bin/signIn/signIn"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const COMPILE_STATUS_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Compile queue status.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "True when status was read.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "pending_count",
            "integer",
            true,
            false,
            "Number of pending request files waiting to be merged.",
            Some("3"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "run_count",
            "integer",
            true,
            false,
            "Number of recorded merged compile runs.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "latest_log",
            "string",
            false,
            true,
            "Latest compile run log path, if any.",
            Some("/home/bin/webclx/compile/runs/20260612T095400-1234/run.log"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "pending_requests",
            "array",
            true,
            false,
            "Detailed pending compile request summaries waiting in the debounce queue.",
            Some(
                r#"[{"request_id":"1712640000000000000-1234","project":"signIn","source_terminal_id":"s1547","source_terminal_name":"signIn_5","source_tmux_session":"webclx_s1547","command":["cargo","build","--release"]}]"#,
            ),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "runs",
            "array",
            true,
            false,
            "Recorded merged compile runs, or only the active newest run when include_history=false.",
            Some(
                r#"[{"run_id":"20260612T095400-1234","status":"success","request_count":2,"projects":["webClx"],"source_terminal_ids":["s1547"],"source_terminal_names":["webClx_1"],"source_tmux_sessions":["webclx_s1547"],"log_path":"/home/bin/webclx/compile/runs/20260612T095400-1234/run.log"}]"#,
            ),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);
