use crate::fields::*;
use crate::schema::*;

pub(crate) const DIRECTORY_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Directory listing response.",
    &[
        field(
            "path",
            "string",
            true,
            false,
            "Workspace-relative path of the listed directory.",
            Some("src"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "display_path",
            "string",
            true,
            false,
            "Human-readable absolute path.",
            Some("/home/codes/webClx/src"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "parent_path",
            "string",
            true,
            true,
            "Workspace-relative parent path if available.",
            Some(""),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "entries",
            "array<object>",
            true,
            false,
            "Directory children.",
            None,
            EMPTY_TEXTS,
            DIRECTORY_ENTRY_FIELDS,
        ),
    ],
);

pub(crate) const FILE_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "File read response.",
    &[
        field(
            "path",
            "string",
            true,
            false,
            "Workspace-relative file path.",
            Some("src/main.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "display_path",
            "string",
            true,
            false,
            "Human-readable absolute path.",
            Some("/home/codes/webClx/src/main.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "editable",
            "boolean",
            true,
            false,
            "Whether inline editing is allowed.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "size",
            "integer",
            true,
            false,
            "File size in bytes.",
            Some("8192"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "content",
            "string",
            true,
            false,
            "UTF-8 text content. May be empty when editable is false.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "message",
            "string",
            true,
            true,
            "Explanation for non-editable files.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_FILE_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Save a UTF-8 text file.",
    &[
        field(
            "path",
            "string",
            true,
            false,
            "Workspace-relative file path to save.",
            Some("src/main.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "content",
            "string",
            true,
            false,
            "New UTF-8 file content.",
            Some("fn main() {}"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_FILE_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "File save confirmation.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the save succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "saved_bytes",
            "integer",
            true,
            false,
            "Number of bytes written.",
            Some("42"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const RENAME_PATH_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Rename a workspace file or directory without moving it to another directory.",
    &[
        field(
            "path",
            "string",
            true,
            false,
            "Workspace-relative file or directory path to rename.",
            Some("src/main.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "name",
            "string",
            true,
            false,
            "New basename. It must not contain path separators.",
            Some("lib.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const RENAME_PATH_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Rename confirmation.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the rename succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "old_path",
            "string",
            true,
            false,
            "Previous workspace-relative path.",
            Some("src/main.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "path",
            "string",
            true,
            false,
            "New workspace-relative path.",
            Some("src/lib.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "display_path",
            "string",
            true,
            false,
            "Human-readable absolute path after rename.",
            Some("/home/codes/webClx/src/lib.rs"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "kind",
            "string",
            true,
            false,
            "Renamed entry kind.",
            Some("file"),
            FAVORITE_PATH_KIND_VALUES,
            EMPTY_FIELDS,
        ),
    ],
);
