use crate::fields::*;
use crate::schema::*;

pub(crate) const SETTINGS_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Current workspace settings.",
    &[
        field(
            "workspace_dir",
            "string",
            true,
            false,
            "Current workspace root as an accessible absolute directory.",
            Some("/home/codes"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_workspace_dir",
            "string",
            true,
            false,
            "Built-in default workspace root.",
            Some("/home/codes"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user",
            "string",
            true,
            false,
            "Linux user selected for new terminal sessions.",
            Some("root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_terminal_user",
            "string",
            true,
            false,
            "Built-in default Linux user for terminal sessions.",
            Some("root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user_home",
            "string",
            true,
            false,
            "Home directory for the selected terminal user.",
            Some("/home/root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user_shell",
            "string",
            true,
            false,
            "Login shell for the selected terminal user.",
            Some("/bin/bash"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "available_users",
            "array<object>",
            true,
            false,
            "Selectable Linux users dynamically resolved from the system user database.",
            None,
            EMPTY_TEXTS,
            SYSTEM_USER_OPTION_FIELDS,
        ),
        field(
            "terminal_quick_commands",
            "array<object>",
            true,
            false,
            "Configured quick commands shown on the terminal soft keyboard and new-terminal prompt.",
            None,
            EMPTY_TEXTS,
            TERMINAL_QUICK_COMMAND_FIELDS,
        ),
        field(
            "terminal_quick_start_default_key",
            "string",
            true,
            false,
            "Quick command key auto-started after the new-terminal timeout. Empty disables auto-start.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_default_env_vars",
            "array<object>",
            true,
            false,
            "Default environment variables injected into new terminal login shells.",
            None,
            EMPTY_TEXTS,
            TERMINAL_DEFAULT_ENV_VAR_FIELDS,
        ),
        field(
            "default_terminal_quick_commands",
            "array<object>",
            true,
            false,
            "Built-in terminal quick command list.",
            None,
            EMPTY_TEXTS,
            TERMINAL_QUICK_COMMAND_FIELDS,
        ),
        field(
            "default_terminal_quick_start_default_key",
            "string",
            true,
            false,
            "Built-in auto-start quick command key.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_terminal_default_env_vars",
            "array<object>",
            true,
            false,
            "Built-in terminal default environment variable list.",
            None,
            EMPTY_TEXTS,
            TERMINAL_DEFAULT_ENV_VAR_FIELDS,
        ),
        field(
            "host_name",
            "string",
            true,
            false,
            "Current machine hostname reported by the running backend.",
            Some("openeuler"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "show_dot_entries",
            "boolean",
            true,
            false,
            "Whether dot-prefixed files are shown.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "show_all_workspace_sessions",
            "boolean",
            true,
            false,
            "Whether the workspace-page session dropdown lists sessions across all directories.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "desktop_terminal_soft_keyboard_enabled",
            "boolean",
            true,
            false,
            "Whether the terminal page shows the soft keyboard on desktop browsers.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_soft_keyboard_scale",
            "number",
            true,
            false,
            "Soft keyboard size multiplier on the terminal page.",
            Some("1.08"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "favorite_paths",
            "array<object>",
            true,
            false,
            "Saved favorite file and directory paths.",
            None,
            EMPTY_TEXTS,
            FAVORITE_PATH_FIELDS,
        ),
        field(
            "workspace_history",
            "array<object>",
            true,
            false,
            "Saved workspace-history directories.",
            None,
            EMPTY_TEXTS,
            WORKSPACE_HISTORY_FIELDS,
        ),
        field(
            "claude_model_options",
            "array<string>",
            true,
            false,
            "Configured Claude model suggestion list.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_key",
            "string",
            true,
            false,
            "Default top-level config.toml key written when applying auth/API presets.",
            Some("model"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_value",
            "string",
            true,
            false,
            "Default value written to the configured config.toml key when auth/API presets do not override it.",
            Some("gpt-5.4"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_key",
            "string",
            true,
            false,
            "Default second top-level config.toml key written when applying auth/API presets.",
            Some("model_reasoning_effort"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_value",
            "string",
            true,
            false,
            "Default value written to the configured second config.toml key when auth/API presets do not override it.",
            Some("high"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "Settings file path on disk.",
            Some("/home/codes/webClx/webclx-settings.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_SETTINGS_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Partial settings update. Omitted fields keep the current value.",
    &[
        field(
            "workspace_dir",
            "string",
            false,
            true,
            "New workspace root as an existing accessible absolute directory. Blank string resets to the built-in default.",
            Some("/home/codes/webClx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user",
            "string",
            false,
            true,
            "Linux user for new terminal sessions. Blank string resets to root.",
            Some("root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_quick_commands",
            "array<object>",
            false,
            false,
            "Full replacement list of terminal quick commands.",
            None,
            EMPTY_TEXTS,
            TERMINAL_QUICK_COMMAND_FIELDS,
        ),
        field(
            "terminal_quick_start_default_key",
            "string",
            false,
            true,
            "Quick command key auto-started after the new-terminal timeout. Blank disables auto-start.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_default_env_vars",
            "array<object>",
            false,
            false,
            "Full replacement list of default environment variables injected into new terminal sessions.",
            None,
            EMPTY_TEXTS,
            TERMINAL_DEFAULT_ENV_VAR_FIELDS,
        ),
        field(
            "show_dot_entries",
            "boolean",
            false,
            false,
            "Whether to show dot-prefixed entries.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "show_all_workspace_sessions",
            "boolean",
            false,
            false,
            "Whether the workspace-page session dropdown should span all directories.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "desktop_terminal_soft_keyboard_enabled",
            "boolean",
            false,
            false,
            "Whether the terminal page should show the soft keyboard on desktop browsers.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_soft_keyboard_scale",
            "number",
            false,
            false,
            "Soft keyboard size multiplier clamped between 0.90 and 1.30.",
            Some("1.08"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "favorite_paths",
            "array<object>",
            false,
            false,
            "Full replacement list of favorite paths.",
            None,
            EMPTY_TEXTS,
            FAVORITE_PATH_FIELDS,
        ),
        field(
            "workspace_history",
            "array<object>",
            false,
            false,
            "Full replacement list of workspace-history directories.",
            None,
            EMPTY_TEXTS,
            WORKSPACE_HISTORY_FIELDS,
        ),
        field(
            "claude_model_options",
            "array<string>",
            false,
            false,
            "Full replacement list of Claude model suggestions.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_key",
            "string",
            false,
            false,
            "Default top-level config.toml key written when applying auth/API presets.",
            Some("model"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_value",
            "string",
            false,
            false,
            "Default value written to the configured config.toml key when auth/API presets do not override it.",
            Some("gpt-5.4"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_key",
            "string",
            false,
            false,
            "Default second top-level config.toml key written when applying auth/API presets.",
            Some("model_reasoning_effort"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_value",
            "string",
            false,
            false,
            "Default value written to the configured second config.toml key when auth/API presets do not override it.",
            Some("high"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_SETTINGS_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Applied settings snapshot after save.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the save succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "workspace_dir",
            "string",
            true,
            false,
            "Current workspace root after save.",
            Some("/home/codes/webClx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user",
            "string",
            true,
            false,
            "Linux user selected for new terminal sessions after save.",
            Some("root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user_home",
            "string",
            true,
            false,
            "Home directory for the selected terminal user after save.",
            Some("/home/root"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_user_shell",
            "string",
            true,
            false,
            "Login shell for the selected terminal user after save.",
            Some("/bin/bash"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_quick_commands",
            "array<object>",
            true,
            false,
            "Current terminal quick command list after save.",
            None,
            EMPTY_TEXTS,
            TERMINAL_QUICK_COMMAND_FIELDS,
        ),
        field(
            "terminal_quick_start_default_key",
            "string",
            true,
            false,
            "Current auto-start quick command key after save. Empty means disabled.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_default_env_vars",
            "array<object>",
            true,
            false,
            "Current default terminal environment variable list after save.",
            None,
            EMPTY_TEXTS,
            TERMINAL_DEFAULT_ENV_VAR_FIELDS,
        ),
        field(
            "show_dot_entries",
            "boolean",
            true,
            false,
            "Current dot-entry setting after save.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "show_all_workspace_sessions",
            "boolean",
            true,
            false,
            "Current workspace session dropdown scope after save.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "desktop_terminal_soft_keyboard_enabled",
            "boolean",
            true,
            false,
            "Whether the terminal soft keyboard is enabled on desktop browsers after save.",
            Some("false"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "terminal_soft_keyboard_scale",
            "number",
            true,
            false,
            "Current terminal soft keyboard size multiplier after save.",
            Some("1.08"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "favorite_paths",
            "array<object>",
            true,
            false,
            "Current favorite path list.",
            None,
            EMPTY_TEXTS,
            FAVORITE_PATH_FIELDS,
        ),
        field(
            "workspace_history",
            "array<object>",
            true,
            false,
            "Current workspace-history directory list.",
            None,
            EMPTY_TEXTS,
            WORKSPACE_HISTORY_FIELDS,
        ),
        field(
            "claude_model_options",
            "array<string>",
            true,
            false,
            "Current Claude model suggestion list.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_key",
            "string",
            true,
            false,
            "Current default top-level config.toml key after save.",
            Some("model"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_config_value",
            "string",
            true,
            false,
            "Current default value written to the configured config.toml key after save.",
            Some("gpt-5.4"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_key",
            "string",
            true,
            false,
            "Current default second top-level config.toml key after save.",
            Some("model_reasoning_effort"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "codex_secondary_config_value",
            "string",
            true,
            false,
            "Current default value written to the configured second config.toml key after save.",
            Some("high"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);
