use crate::fields::*;
use crate::schema::*;

pub(crate) const APPLY_CURRENT_AUTH_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Apply login-style auth data directly from the current editor form.",
    &[field(
        "auth",
        "object",
        true,
        false,
        "Login-format auth.json payload.",
        None,
        EMPTY_TEXTS,
        AUTH_FILE_FIELDS,
    )],
);

pub(crate) const APPLY_CURRENT_AUTH_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Confirmation that current login auth was applied.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the apply succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "auth_file",
            "string",
            true,
            false,
            "auth.json path written on disk.",
            Some("/home/example/.codex/auth.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "config.toml path that was updated.",
            Some("/home/example/.codex/config.toml"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "account_id",
            "string",
            true,
            false,
            "Account id from the applied auth payload.",
            Some("acct_123456"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const DELETE_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Delete confirmation response.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the delete succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "deleted_id",
            "string",
            true,
            false,
            "Deleted preset id.",
            Some("api-1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const APPLY_AUTH_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Confirmation that a login-style auth preset was applied.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the apply succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset_id",
            "string",
            true,
            false,
            "Applied preset id.",
            Some("auth-1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "name",
            "string",
            true,
            false,
            "Applied preset name.",
            Some("Main login"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "auth_file",
            "string",
            true,
            false,
            "auth.json path written on disk.",
            Some("/home/example/.codex/auth.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "config.toml path that was updated.",
            Some("/home/example/.codex/config.toml"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const APPLY_API_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Confirmation that an API-key preset was applied and verified from disk.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the apply succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset_id",
            "string",
            true,
            false,
            "Applied preset id.",
            Some("api-1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "name",
            "string",
            true,
            false,
            "Applied preset name.",
            Some("OpenAI default"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "auth_file",
            "string",
            true,
            false,
            "auth.json path written on disk.",
            Some("/home/example/.codex/auth.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "config.toml path that was updated.",
            Some("/home/example/.codex/config.toml"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const VERIFY_API_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Read-only verification of a saved API-key preset against auth.json and config.toml.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the verification request completed successfully.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset_id",
            "string",
            true,
            false,
            "Verified preset id.",
            Some("api-1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "name",
            "string",
            true,
            false,
            "Verified preset name.",
            Some("OpenAI default"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "matches",
            "boolean",
            true,
            false,
            "Whether the current credentials, provider settings, and config overrides match the preset.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "current_mode",
            "string",
            true,
            false,
            "Current auth mode derived from auth.json and config.toml.",
            Some("api"),
            CURRENT_AUTH_MODE_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "current_api",
            "object",
            true,
            true,
            "Masked summary of the API configuration currently read from disk.",
            None,
            EMPTY_TEXTS,
            CURRENT_API_FIELDS,
        ),
        field(
            "model",
            "string",
            true,
            true,
            "Current model value read from config.toml, when configured.",
            Some("glm-5.1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "mismatches",
            "array<string>",
            true,
            false,
            "Human-readable mismatch descriptions without secret values.",
            Some(r#"["用户 `root` 的 config 键 `model` 不匹配"]"#),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const APPLY_CLAUDE_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Confirmation that a Claude preset was applied.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the apply succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset_id",
            "string",
            true,
            false,
            "Applied preset id.",
            Some("claude-1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "name",
            "string",
            true,
            false,
            "Applied preset name.",
            Some("Anthropic default"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "settings_file",
            "string",
            true,
            false,
            "Settings file path written on disk.",
            Some("/home/example/.claude/settings.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);
