use crate::fields::*;
use crate::schema::*;

pub(crate) const AUTH_PRESET_LIST_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "List of login-style auth presets and current auth state.",
    &[
        field(
            "auth_file",
            "string",
            true,
            false,
            "Active auth.json path.",
            Some("/home/example/.codex/auth.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "Active config.toml path.",
            Some("/home/example/.codex/config.toml"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "preset_file",
            "string",
            true,
            false,
            "Preset storage file path.",
            Some("/home/codes/webClx/webclx-auth-presets.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "current_mode",
            "string",
            true,
            false,
            "Current auth mode derived from auth.json and config.toml.",
            Some("auth"),
            CURRENT_AUTH_MODE_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "current_auth",
            "object",
            true,
            true,
            "Current login auth summary when available.",
            None,
            EMPTY_TEXTS,
            CURRENT_AUTH_FIELDS,
        ),
        field(
            "current_api",
            "object",
            true,
            true,
            "Current API mode summary when available.",
            None,
            EMPTY_TEXTS,
            CURRENT_API_FIELDS,
        ),
        field(
            "current_auth_error",
            "string",
            true,
            true,
            "Error reading auth.json, if any.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "current_config_error",
            "string",
            true,
            true,
            "Error reading config.toml, if any.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "presets",
            "array<object>",
            true,
            false,
            "Saved login-style auth presets.",
            None,
            EMPTY_TEXTS,
            AUTH_PRESET_SUMMARY_FIELDS,
        ),
    ],
);

pub(crate) const API_PRESET_LIST_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "List of API-key presets and current API state.",
    &[
        field(
            "auth_file",
            "string",
            true,
            false,
            "Active auth.json path.",
            Some("/home/example/.codex/auth.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_file",
            "string",
            true,
            false,
            "Active config.toml path.",
            Some("/home/example/.codex/config.toml"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "preset_file",
            "string",
            true,
            false,
            "Preset storage file path.",
            Some("/home/codes/webClx/webclx-api-presets.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "current_mode",
            "string",
            true,
            false,
            "Current auth mode derived from auth.json and config.toml.",
            Some("api"),
            CURRENT_AUTH_MODE_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "current_auth",
            "object",
            true,
            true,
            "Current login auth summary when available.",
            None,
            EMPTY_TEXTS,
            CURRENT_AUTH_FIELDS,
        ),
        field(
            "current_api",
            "object",
            true,
            true,
            "Current API mode summary when available.",
            None,
            EMPTY_TEXTS,
            CURRENT_API_FIELDS,
        ),
        field(
            "current_auth_error",
            "string",
            true,
            true,
            "Error reading auth.json, if any.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "current_config_error",
            "string",
            true,
            true,
            "Error reading config.toml, if any.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "presets",
            "array<object>",
            true,
            false,
            "Saved API-key presets.",
            None,
            EMPTY_TEXTS,
            API_PRESET_SUMMARY_FIELDS,
        ),
    ],
);

pub(crate) const CLAUDE_PRESET_LIST_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "List of Claude presets and current Claude settings state.",
    &[
        field(
            "settings_file",
            "string",
            true,
            false,
            "Active Claude settings file.",
            Some("/home/example/.claude/settings.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "preset_file",
            "string",
            true,
            false,
            "Preset storage file path.",
            Some("/home/codes/webClx/webclx-claude-presets.json"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "current_claude",
            "object",
            true,
            true,
            "Current Claude settings summary when available.",
            None,
            EMPTY_TEXTS,
            CURRENT_CLAUDE_FIELDS,
        ),
        field(
            "current_settings_error",
            "string",
            true,
            true,
            "Error reading current settings file, if any.",
            None,
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "presets",
            "array<object>",
            true,
            false,
            "Saved Claude presets.",
            None,
            EMPTY_TEXTS,
            CLAUDE_PRESET_SUMMARY_FIELDS,
        ),
    ],
);
