use crate::fields::*;
use crate::schema::*;

pub(crate) const CODEX_OAUTH_SESSION_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Codex official OAuth device-login session state.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the request succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "session_id",
            "string",
            true,
            false,
            "Temporary server-side session id used for polling.",
            Some("codex_xxx"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "status",
            "string",
            true,
            false,
            "Current device-login status.",
            Some("pending"),
            &["pending", "completed", "error", "expired"],
            EMPTY_FIELDS,
        ),
        field(
            "verification_url",
            "string",
            true,
            false,
            "Official Codex device-login page.",
            Some("https://auth.openai.com/codex/device"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "authorize_url",
            "string",
            true,
            false,
            "Official Codex device-login page with the user code prefilled when available.",
            Some("https://auth.openai.com/codex/device?code=ABCD-EFGH"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "user_code",
            "string",
            true,
            false,
            "User code that must be entered on the official login page.",
            Some("ABCD-EFGH"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "poll_interval_seconds",
            "integer",
            true,
            false,
            "Suggested polling interval for the web UI.",
            Some("5"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "created_at",
            "integer",
            true,
            false,
            "Unix timestamp when the session was created.",
            Some("1712640000"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "updated_at",
            "integer",
            true,
            false,
            "Unix timestamp when the session last changed state.",
            Some("1712640005"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "expires_at",
            "integer",
            true,
            false,
            "Unix timestamp when the device-login session expires.",
            Some("1712640900"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "error",
            "string",
            false,
            true,
            "Error message when status is error or expired.",
            Some("等待官网登录超时，请重新发起登录。"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "auth",
            "object",
            false,
            true,
            "auth.json payload returned after successful official login.",
            None,
            EMPTY_TEXTS,
            AUTH_FILE_FIELDS,
        ),
        field(
            "details",
            "object",
            false,
            true,
            "Derived account details extracted from the returned tokens.",
            None,
            EMPTY_TEXTS,
            AUTH_PRESET_DETAILS_FIELDS,
        ),
        field(
            "suggested_name",
            "string",
            false,
            true,
            "Suggested preset name for the newly logged-in account.",
            Some("user@example.com · Personal"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);
