use crate::fields::*;
use crate::schema::*;

pub(crate) const SAVE_AUTH_PRESET_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Create or update a login-style auth preset.",
    &[
        field(
            "name",
            "string",
            false,
            false,
            "Optional display name. Empty uses an auto-generated name.",
            Some("Main login"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "details",
            "object",
            false,
            false,
            "Optional metadata to save with the preset.",
            None,
            EMPTY_TEXTS,
            AUTH_PRESET_DETAILS_FIELDS,
        ),
        field(
            "config_key",
            "string",
            false,
            true,
            "Optional top-level config.toml key override. Empty uses the settings default key.",
            Some("model"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_value",
            "string",
            false,
            true,
            "Optional value override written to the chosen config.toml key. Empty uses the settings default value.",
            Some("glm-5.1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "secondary_config_key",
            "string",
            false,
            true,
            "Optional second top-level config.toml key override. Empty uses the settings default second key.",
            Some("model_reasoning_effort"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "secondary_config_value",
            "string",
            false,
            true,
            "Optional second value override written to the chosen config.toml key. Empty uses the settings default second value.",
            Some("high"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "auth",
            "object",
            true,
            false,
            "Login-format auth.json payload.",
            None,
            EMPTY_TEXTS,
            AUTH_FILE_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_AUTH_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Saved login-style auth preset.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the save succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset",
            "object",
            true,
            false,
            "Saved auth preset summary.",
            None,
            EMPTY_TEXTS,
            AUTH_PRESET_SUMMARY_FIELDS,
        ),
    ],
);

pub(crate) const REFRESH_ALL_AUTH_PRESETS_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Batch refresh result for saved login-style auth presets.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the batch request completed.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "total",
            "integer",
            true,
            false,
            "How many auth presets were considered.",
            Some("5"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "success_count",
            "integer",
            true,
            false,
            "How many auth presets refreshed successfully.",
            Some("4"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "failure_count",
            "integer",
            true,
            false,
            "How many auth presets failed to refresh.",
            Some("1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "failures",
            "array",
            true,
            false,
            "Per-preset failures encountered during the batch refresh.",
            None,
            EMPTY_TEXTS,
            &[field(
                "[]",
                "object",
                false,
                false,
                "Failed preset item.",
                None,
                EMPTY_TEXTS,
                &[
                    field(
                        "preset_id",
                        "string",
                        true,
                        false,
                        "Failed preset id.",
                        Some("auth-1712640000"),
                        EMPTY_TEXTS,
                        EMPTY_FIELDS,
                    ),
                    field(
                        "name",
                        "string",
                        true,
                        false,
                        "Failed preset display name.",
                        Some("Main login"),
                        EMPTY_TEXTS,
                        EMPTY_FIELDS,
                    ),
                    field(
                        "error",
                        "string",
                        true,
                        false,
                        "Failure message.",
                        Some("刷新额度失败: HTTP 403"),
                        EMPTY_TEXTS,
                        EMPTY_FIELDS,
                    ),
                ],
            )],
        ),
    ],
);

pub(crate) const SAVE_API_PRESET_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Create or update an API-key preset.",
    &[
        field(
            "name",
            "string",
            false,
            false,
            "Optional display name. Empty uses an auto-generated name.",
            Some("OpenAI default"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "provider_name",
            "string",
            false,
            false,
            "Optional provider name. Empty derives from base_url.",
            Some("OpenAI"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "api_key",
            "string",
            true,
            false,
            "API key to save and later write into auth.json.",
            Some("sk-live-secret"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "base_url",
            "string",
            true,
            false,
            "Provider base URL. Trailing slash is normalized away.",
            Some("https://api.openai.com/v1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "management_url",
            "string",
            false,
            true,
            "Optional management page URL.",
            Some("https://platform.openai.com/api-keys"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "management_url_same_as_base",
            "boolean",
            false,
            false,
            "When true, the backend stores management_url as the same value as base_url.",
            Some("true"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_key",
            "string",
            false,
            true,
            "Optional top-level config.toml key override. Empty uses the settings default key.",
            Some("model"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "config_value",
            "string",
            false,
            true,
            "Optional value override written to the chosen config.toml key. Empty uses the settings default value.",
            Some("glm-5.1"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "secondary_config_key",
            "string",
            false,
            true,
            "Optional second top-level config.toml key override. Empty uses the settings default second key.",
            Some("model_reasoning_effort"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "secondary_config_value",
            "string",
            false,
            true,
            "Optional second value override written to the chosen config.toml key. Empty uses the settings default second value.",
            Some("high"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_API_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Saved API-key preset.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the save succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset",
            "object",
            true,
            false,
            "Saved API preset summary.",
            None,
            EMPTY_TEXTS,
            API_PRESET_SUMMARY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_CLAUDE_PRESET_REQUEST_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Create or update a Claude preset.",
    &[
        field(
            "name",
            "string",
            false,
            false,
            "Optional display name. Empty uses an auto-generated name.",
            Some("Anthropic default"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "provider_name",
            "string",
            false,
            false,
            "Optional provider name. Empty derives from base_url.",
            Some("Anthropic"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "auth_token",
            "string",
            true,
            false,
            "Claude auth token.",
            Some("sk-ant-secret"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "base_url",
            "string",
            true,
            false,
            "Claude-compatible base URL. Trailing slash is normalized away.",
            Some("https://api.anthropic.com"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "management_url",
            "string",
            false,
            true,
            "Optional management page URL.",
            Some("https://console.anthropic.com/settings/keys"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_haiku_model",
            "string",
            false,
            true,
            "Optional official Haiku model override. Alias small_fast_model is also accepted.",
            Some("claude-3-5-haiku-latest"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_sonnet_model",
            "string",
            false,
            true,
            "Optional official Sonnet model override.",
            Some("claude-sonnet-4-0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "default_opus_model",
            "string",
            false,
            true,
            "Optional official Opus model override.",
            Some("claude-opus-4-0"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
        field(
            "third_party_model",
            "string",
            false,
            true,
            "Optional single custom model. Must not be mixed with the official trio fields.",
            Some("claude-3-7-sonnet"),
            EMPTY_TEXTS,
            EMPTY_FIELDS,
        ),
    ],
);

pub(crate) const SAVE_CLAUDE_PRESET_RESPONSE_BODY: ApiBodySchema = body(
    "application/json",
    "object",
    "Saved Claude preset.",
    &[
        field(
            "ok",
            "boolean",
            true,
            false,
            "Whether the save succeeded.",
            Some("true"),
            BOOL_VALUES,
            EMPTY_FIELDS,
        ),
        field(
            "preset",
            "object",
            true,
            false,
            "Saved Claude preset summary.",
            None,
            EMPTY_TEXTS,
            CLAUDE_PRESET_SUMMARY_FIELDS,
        ),
    ],
);
